# Generated by Django 4.0.4 on 2022-05-26 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena_format', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='format_filmu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='rodzaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj_format', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmy.cena')),
                ('format', models.ManyToManyField(related_name='rodzaj', related_query_name='cena', to='filmy.format_filmu')),
                ('rodzaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmy.rodzaj')),
            ],
        ),
    ]
